"""add_shiprocket_shipping_fields

Revision ID: 07535e5405fe
Revises: 8e6e389c9c60
Create Date: 2026-05-18 18:11:21.140129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07535e5405fe'
down_revision: Union[str, Sequence[str], None] = '8e6e389c9c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shiprocket_order_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shiprocket_shipment_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('awb_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('courier_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('serviceable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('orders', sa.Column('pickup_scheduled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('orders', sa.Column('manifest_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'manifest_generated')
    op.drop_column('orders', 'pickup_scheduled')
    op.drop_column('orders', 'serviceable')
    op.drop_column('orders', 'courier_name')
    op.drop_column('orders', 'awb_code')
    op.drop_column('orders', 'shiprocket_shipment_id')
    op.drop_column('orders', 'shiprocket_order_id')
    # ### end Alembic commands ###
