"""add order processing flags

Revision ID: 0fc969015e81
Revises: 59425a274cc2
Create Date: 2026-02-19 01:40:26.884826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc969015e81'
down_revision: Union[str, Sequence[str], None] = '59425a274cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        'orders',
        sa.Column(
            'user_email_sent',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False
        )
    )

    op.add_column(
        'orders',
        sa.Column(
            'admin_notified',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False
        )
    )

    op.add_column(
        'orders',
        sa.Column(
            'invoice_url',
            sa.String(),
            nullable=True
        )
    )

    op.add_column(
        'orders',
        sa.Column(
            'invoice_number',
            sa.String(length=50),
            nullable=True
        )
    )

    # Optional but recommended:
    op.create_unique_constraint(
        "uq_invoice_number",
        "orders",
        ["invoice_number"]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'invoice_url')
    op.drop_column('orders', 'invoice_generated')
    op.drop_column('orders', 'admin_notified')
    op.drop_column('orders', 'user_email_sent')
    # ### end Alembic commands ###
