"""make coupons dynamic buy n get m

Revision ID: 14aa8a9faa2e
Revises: 0eee69bec31d
Create Date: 2026-04-28 13:05:32.099532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14aa8a9faa2e'
down_revision: Union[str, Sequence[str], None] = '0eee69bec31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE coupon_rule_type RENAME VALUE 'B2G1_SAME_DIMENSION' TO 'BUY_N_GET_M_SAME_DIMENSION'"
    )
    op.add_column('coupons', sa.Column('required_qty', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('free_qty', sa.Integer(), nullable=True))
    op.create_check_constraint(
        'ck_coupon_percent_off_range',
        'coupons',
        'percent_off IS NULL OR (percent_off > 0 AND percent_off <= 100)',
    )
    op.create_check_constraint(
        'ck_coupon_required_qty_positive',
        'coupons',
        'required_qty IS NULL OR required_qty > 0',
    )
    op.create_check_constraint(
        'ck_coupon_free_qty_positive',
        'coupons',
        'free_qty IS NULL OR free_qty > 0',
    )
    op.create_check_constraint(
        'ck_coupon_required_gt_free',
        'coupons',
        'required_qty IS NULL OR free_qty IS NULL OR required_qty > free_qty',
    )
    op.add_column('orders', sa.Column('coupon_required_qty', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('coupon_free_qty', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('coupon_matched_dimension', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'coupon_matched_dimension')
    op.drop_column('orders', 'coupon_free_qty')
    op.drop_column('orders', 'coupon_required_qty')
    op.drop_constraint('ck_coupon_required_gt_free', 'coupons', type_='check')
    op.drop_constraint('ck_coupon_free_qty_positive', 'coupons', type_='check')
    op.drop_constraint('ck_coupon_required_qty_positive', 'coupons', type_='check')
    op.drop_constraint('ck_coupon_percent_off_range', 'coupons', type_='check')
    op.drop_column('coupons', 'free_qty')
    op.drop_column('coupons', 'required_qty')
    op.execute(
        "ALTER TYPE coupon_rule_type RENAME VALUE 'BUY_N_GET_M_SAME_DIMENSION' TO 'B2G1_SAME_DIMENSION'"
    )
    # ### end Alembic commands ###
