"""added invoice_number column

Revision ID: 51267894b05d
Revises: 0fc969015e81
Create Date: 2026-02-24 13:02:28.053141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51267894b05d'
down_revision: Union[str, Sequence[str], None] = '0fc969015e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('invoice_number', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'orders', ['invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'invoice_number')
    # ### end Alembic commands ###
