"""add idempotency key to orders

Revision ID: 59425a274cc2
Revises: 362c1f4bb63d
Create Date: 2026-01-20 12:44:49.802703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59425a274cc2'
down_revision: Union[str, Sequence[str], None] = '362c1f4bb63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=64), nullable=False))
    op.alter_column('orders', 'order_status',
               existing_type=postgresql.ENUM('CREATED', 'CONFIRMED', 'CANCELLED', 'SHIPPED', 'FULFILLED', name='order_status'),
               nullable=False)
    op.create_unique_constraint('uq_user_idempotency_key', 'orders', ['user_id', 'idempotency_key'])
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('CREATED', 'SUCCESS', 'FAILED', name='payment_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('CREATED', 'SUCCESS', 'FAILED', name='payment_status'),
               nullable=True)
    op.drop_constraint('uq_user_idempotency_key', 'orders', type_='unique')
    op.alter_column('orders', 'order_status',
               existing_type=postgresql.ENUM('CREATED', 'CONFIRMED', 'CANCELLED', 'SHIPPED', 'FULFILLED', name='order_status'),
               nullable=True)
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
