"""Added discounted price column

Revision ID: 63077bb11bd7
Revises: af3124420de8
Create Date: 2025-11-12 08:13:54.484804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63077bb11bd7'
down_revision: Union[str, Sequence[str], None] = 'af3124420de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discounted_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discounted_price')
    # ### end Alembic commands ###
