"""Added dimension price multiplier

Revision ID: 647c2a2e5d27
Revises: 63077bb11bd7
Create Date: 2025-11-13 12:02:23.516319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647c2a2e5d27'
down_revision: Union[str, Sequence[str], None] = '63077bb11bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dimension_pricing_id'), 'dimension_pricing', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dimension_pricing_id'), table_name='dimension_pricing')
    op.drop_table('dimension_pricing')
    # ### end Alembic commands ###
