"""Added dimension in order_item table

Revision ID: 7e8e10000e29
Revises: 0dea64dce98b
Create Date: 2025-12-04 01:00:08.608140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8e10000e29'
down_revision: Union[str, Sequence[str], None] = '0dea64dce98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('dimension', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'dimension')
    # ### end Alembic commands ###
