"""Added column for user  name in Address book

Revision ID: 86445712e2a7
Revises: 69802c988ebe
Create Date: 2025-11-27 13:23:12.241358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86445712e2a7'
down_revision: Union[str, Sequence[str], None] = '69802c988ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'name')
    # ### end Alembic commands ###
