"""Updated order table for generic payment methods

Revision ID: e7c069da6150
Revises: 7e8e10000e29
Create Date: 2025-12-12 15:27:08.093081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7c069da6150'
down_revision: Union[str, Sequence[str], None] = '7e8e10000e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_phone_number', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_address_line', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_city', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_state', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_zip_code', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('delivery_address_type', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('payment_gateway_order_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('order_status', sa.String(), nullable=True))
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_column('orders', 'razorpay_order_id')
    op.drop_column('orders', 'status')
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('signature', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('raw_response', sa.JSON(), nullable=True))
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_column('payments', 'razorpay_payment_id')
    op.drop_column('payments', 'razorpay_signature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_signature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'raw_response')
    op.drop_column('payments', 'signature')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'payment_method')
    op.add_column('orders', sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'FAILED', 'CANCELLED', name='orderstatus'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('razorpay_order_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_column('orders', 'order_status')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_gateway_order_id')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'delivery_address_type')
    op.drop_column('orders', 'delivery_zip_code')
    op.drop_column('orders', 'delivery_state')
    op.drop_column('orders', 'delivery_city')
    op.drop_column('orders', 'delivery_address_line')
    op.drop_column('orders', 'delivery_phone_number')
    op.drop_column('orders', 'delivery_name')
    # ### end Alembic commands ###
